"""empty message

Revision ID: 177910723f96
Revises: ae167d5a11fa
Create Date: 2018-12-27 23:09:38.143507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '177910723f96'
down_revision = 'ae167d5a11fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'Websitedetails', 'users', ['user_id'], ['uid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Websitedetails', type_='foreignkey')
    # ### end Alembic commands ###
