"""empty message

Revision ID: 245833dbb251
Revises: 55b41bc9e46a
Create Date: 2018-12-29 06:05:48.651723

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '245833dbb251'
down_revision = '55b41bc9e46a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Websitedetails', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Websitedetails', 'users', ['user_id'], ['uid'])
    op.drop_constraint('users_ibfk_1', 'users', type_='foreignkey')
    op.drop_column('users', 'details_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('details_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('users_ibfk_1', 'users', 'Websitedetails', ['details_id'], ['wid'])
    op.drop_constraint(None, 'Websitedetails', type_='foreignkey')
    op.drop_column('Websitedetails', 'user_id')
    # ### end Alembic commands ###
