"""empty message

Revision ID: 4a998ad00485
Revises: 177910723f96
Create Date: 2018-12-27 23:12:15.184433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a998ad00485'
down_revision = '177910723f96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Websitedetails', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Websitedetails', 'users', ['user_id'], ['uid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Websitedetails', type_='foreignkey')
    op.drop_column('Websitedetails', 'user_id')
    # ### end Alembic commands ###
