"""empty message

Revision ID: 55b41bc9e46a
Revises: c05427bfee3d
Create Date: 2018-12-29 05:48:33.871341

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '55b41bc9e46a'
down_revision = 'c05427bfee3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Websitedetails_ibfk_1', 'Websitedetails', type_='foreignkey')
    op.drop_column('Websitedetails', 'uid')
    op.add_column('users', sa.Column('details_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'Websitedetails', ['details_id'], ['wid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'details_id')
    op.add_column('Websitedetails', sa.Column('uid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('Websitedetails_ibfk_1', 'Websitedetails', 'users', ['uid'], ['uid'])
    # ### end Alembic commands ###
