"""empty message

Revision ID: 5ca76885ff50
Revises: 4a998ad00485
Create Date: 2018-12-27 23:13:44.096230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ca76885ff50'
down_revision = '4a998ad00485'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Websitedetails', sa.Column('uid', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Websitedetails', 'users', ['uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Websitedetails', type_='foreignkey')
    op.drop_column('Websitedetails', 'uid')
    # ### end Alembic commands ###
