"""empty message

Revision ID: aea7be17dce3
Revises: 
Create Date: 2018-12-26 04:55:47.632201

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aea7be17dce3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Websitedetails',
    sa.Column('wid', sa.Integer(), nullable=False),
    sa.Column('websitename', sa.String(length=100), nullable=True),
    sa.Column('websiteurl', sa.Text(length=65535), nullable=True),
    sa.Column('websitedetails', sa.UnicodeText(), nullable=True),
    sa.Column('savedat', sa.DateTime(), nullable=True),
    sa.Column('editedat', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('wid')
    )
    op.drop_index('email', table_name='students')
    op.drop_index('username', table_name='students')
    op.drop_table('students')
    op.alter_column('users', 'firstname',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'lastname',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'pwdhash',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'pwdhash',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'lastname',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'firstname',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.create_table('students',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('city', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('username', 'students', ['username'], unique=True)
    op.create_index('email', 'students', ['email'], unique=True)
    op.drop_table('Websitedetails')
    # ### end Alembic commands ###
