"""empty message

Revision ID: c05427bfee3d
Revises: 183c704e4844
Create Date: 2018-12-29 05:30:59.890239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c05427bfee3d'
down_revision = '183c704e4844'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Websitedetails',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('wid', sa.Integer(), nullable=False),
    sa.Column('websitename', sa.String(length=100), nullable=True),
    sa.Column('websiteurl', sa.Text(length=65535), nullable=True),
    sa.Column('websitedetails', sa.UnicodeText(), nullable=True),
    sa.Column('savedat', sa.DateTime(), nullable=True),
    sa.Column('editedat', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('wid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Websitedetails')
    # ### end Alembic commands ###
