"""empty message

Revision ID: fed241c44b04
Revises: aea7be17dce3
Create Date: 2018-12-27 22:43:31.409700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fed241c44b04'
down_revision = 'aea7be17dce3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Websitedetails', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Websitedetails', 'users', ['user_id'], ['uid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Websitedetails', type_='foreignkey')
    op.drop_column('Websitedetails', 'user_id')
    # ### end Alembic commands ###
